[package]
name = "lunar_common"
version = "0.1.0"
edition = "2018"

[dependencies]
lunar_macros = { path = "../macros" }
lunar_location = { path = "../location" }
lunar_tokens = { path = "../tokens" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0.0"
thiserror = "*"
