[package]
name = "lunar_tokens"
version = "0.1.0"
edition = "2021"

[dependencies]
lunar_location = { path = "../location" }
lunar_traits = { path = "../traits" }
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
smol_str = "0.1.21"
