[package]
name = "lunar_ast"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
lunar_macros = { path = "../macros" }
smol_str = { version = "*", features = ["serde"] }
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
