[package]
name = "lunar_errors"
version = "0.1.0"
edition = "2021"

[dependencies]
lunar_ast = { path = "../ast" }
lunar_shared = { path = "../shared" }
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
