# From: https://github.com/rojo-rbx/rojo/blob/master/.github/workflows/ci.yml
# Licensed under MPL 2.0 License: https://github.com/rojo-rbx/rojo/blob/master/LICENSE.txt
name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable, "1.60.0"]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          profile: minimal
          override: true

      - name: Build debug
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }}

      - name: Test all benches
        if: matrix.benches
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --benches ${{ matrix.features }}
