name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable, "1.60.0"]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Rust toolchain
      run: rustup default ${{ matrix.rust_version }}

    - name: Build
      run: cargo build --bin lunar_driver --locked --verbose

    - name: Run tests
      run: |
        cargo test --locked --verbose
        cargo run --bin test-suite --release --locked --verbose --features scripts

    - name: Rustfmt and Clippy
      run: |
        cargo fmt -- --check
        cargo clippy
      if: matrix.rust_version == 'stable'
