# Taken from: https://github.com/rojo-rbx/rojo/blob/master/.github/workflows/release.yml
# Licensed under MPL 2.0 License: https://github.com/rojo-rbx/rojo/blob/master/LICENSE.txt
name: Release

on:
  push:
    tags: ["*"]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Build release binary
        run: cargo build --verbose --locked --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: lunar-win64
          path: target/release/lunar.exe

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Build release binary
        run: |
          source $HOME/.cargo/env
          cargo build --verbose --locked --release
        env:
          OPENSSL_STATIC: 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: lunar-macos
          path: target/release/lunar

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Build
        run: cargo build --locked --verbose --release
        env:
          OPENSSL_STATIC: 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: lunar-linux
          path: target/release/rojo
