# Taken from: https://github.com/rojo-rbx/rojo/blob/master/.github/workflows/release.yml
# Licensed under MPL 2.0 License: https://github.com/rojo-rbx/rojo/blob/master/LICENSE.txt
name: Release

on:
  push:
    tags: ["*"]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setting toolchain to nightly
        run: rustup default nightly

      - name: Build release binary
        run: cargo build --verbose --release --features multithreading

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: salite-win64
          path: target/release/salite.exe

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Setting toolchain to nightly
        run: rustup default nightly

      - name: Build release binary
        run: |
          source $HOME/.cargo/env
          cargo build --verbose --release --features multithreading

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: salite-macos-x86_64
          path: target/release/salite

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setting toolchain to nightly
        run: rustup default nightly

      - name: Build
        run: cargo build --verbose --release --features multithreading

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: salite-linux
          path: target/release/salite
